{
 "title": "Tenant Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant ID", "query": { "query": "label_values(tenant)" } }
  ]
 },
 "panels": [
  {
   "title": "Metric Sample Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(metric_sample_count_total{}[$__interval]))  ",
     "legendFormat": "Metric ingestion rate"
    }
   ]
  },
  {
   "title": "Flows Sample Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flow_sample_count_total[$__interval]))  ",
     "legendFormat": "Flow ingestion rate"
    }
   ]
  },
  {
   "title": "Event Sample Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(event_sample_count_total[$__interval]))  ",
     "legendFormat": "Event ingestion rate"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "node_count", "legendFormat": "Node count" }
   ]
  }
 ]
}